### PR TITLE
tag selector for newEntry form

### PR DESCRIPTION
**Pull request by egolus**
(this is far from ready to merge)

see: #42

### CODE REVIEW

**Comment by baudren** [comment]
Nice first draft. A few comments:
- it would be nice to be able to click on the whole line to check the tag, instead of just on the checkbox (right now, it enters editing the tag name...).
- we have to think about both keyboard and mouse support, when the filter will be implemented, that is, if we start typing a tag, and there is only one possibility, typing `Enter` should add the tag, not try to validate the whole form.
- As discussed in gitter - could be nice to have the selected tags displayed as mail recipients (like standard gmail interface, _e.g._)

**Comment by baudren** [comment]
Still to do:
- [x] ~~convert the `;` to `,` once finished editing (or during?)~~
- [x] ~~would it be possible that the first entry gets highlighted, to understand that if we press enter, this will hapen?~~ Won't fix for now
- [x] ~~initial focus should be on the `title` line, not the `tags`~~
- [x] ~~display the drop down on click (show a small arrow, like a standard combo box, for mouse oriented people)~~

**Comment by egolus** [comment]
I rebased this, so make sure to get the right state!

**Comment by baudren** [comment]
It can be merged.

**Pull request merged**
