### PR TITLE
34 Button `Refresh` in Preview

### PR DESCRIPTION
**Pull request by egolus**
This adds a refresh button to the Preview page (right side, over the scroll area)

### CODE REVIEW

**Comment by baudren** [comment]
Thanks @egolus,

the placement of the button seems a bit awkward (problem related somehow to #49). This could be a good place to try a toolbar implementation, no? Do you want to take a go at it?

**Comment by egolus** [comment]
OK, I'll put a toolbar in `Preview`, so under the tabbar. If we like it, we can do the same for `Editing`

**Comment by baudren** [comment]
Travis failing to merge seems no problem - it seems git got confused over a trivial thing.

However - the implementation does not seem to work for me (Win 8.1). The toolbar is fixed to the three options `Up`, `New N`, `New F`, and whatever I switch tab to, stay there. I get repeatedly this error:

``` python
Traceback (most recent call last):
  File "noteorganiser/NoteOrganiser.py", line 271, in showActiveToolBar
    self.library.toolbar.setVisible(False)
AttributeError: 'Library' object has no attribute 'toolbar'
```

Surprisingly enough, the tests pass.

**Comment by egolus** [comment]
Aah, you're right, I forgot to change this to ´library.shelves.toolbar´
The tests don't need the toolbar to be visible to 'click' on it, it seems

Am 25. Juni 2015 09:29:12 MESZ, schrieb Benjamin Audren <notifications@github.com>:

**Comment by egolus** [comment]
Aah, you're right, I forgot to change this to `library.shelves.toolbar` The tests don't need the toolbar to be visible to 'click' on it, it seems

**Comment by egolus** [comment]
This should fix the toolbar

**Comment by baudren** [comment]
It's looking good!

I will test tonight on linux to see how it looks there, then will merge it. Thank you!

**Comment by baudren** [comment]
I think that the separator behaves strangely on my machine. There is a physical separation between the `save` and the one on the left, but no visual indication of it. Is there anything on your side? Do you find it visually clear enough?

**Comment by egolus** [comment]
separator
there's a thin line, but I have to admit, it's very thin

**Comment by egolus** [comment]
separator2
we could use 3 separators to make it a bit stronger..

the other question is if it is strong enough when we use icons instead of text

**Comment by baudren** [comment]
Well, one or three, either is invisible on my linux setup. On win8.1, no problem. I will try to see if it is a known bug.

In terms of layout, I would put the Save and Reload to the left, rather than to the right.

I was also thinking that a more [ribbon like](https://en.wikipedia.org/wiki/Ribbon_%28computing%29) appearance could work better, no? Having maybe a tab for each panel (Library, Editing, Preview), and the related options in these tabs?

**Comment by baudren** [comment]
Since the functionnality is added, and working, I could merge this, right?

**Pull request merged**
