### PR TITLE
Table of Content

### PR DESCRIPTION
**Pull request by egolus**
Here's the TOC. Standard state is not to use it, toggleable by the menuentry

### CODE REVIEW

**Comment by baudren** [comment]
Hey, nice feature!

Small comment: after having generated the preview, when toggling between displaying TOC or not displaying it, the refresh is not done on selecting the option, but only on the next action (selecting a filter, etc...). Could you do it such that it is refreshed when toggling?

**Comment by baudren** [comment]
And by the way, you can check the comment left by @landscape-bot to see some style problems (the `if bla == True` is considered bad practice, you can use `if bla` simply, for instance).

**Comment by egolus** [comment]
I fixed the style issues

About the refresh: do you hold the currently used tags in preview somewhere? I only found `extracted_tags` that holds the remaining tags for further filtering, right?

**Comment by baudren** [comment]
You are right - having it in a separated function would be ideal. But is `loadNotebook` really the function we want to call? Shouldn't it be enough to refresh the file from disk, *i.e.* only reloading the html, and not recomputing it?

**Comment by egolus** [comment]
the TOC is a parameter for pandoc, so we need to recompute the html with or without `--toc`

**Comment by baudren** [comment]
Fair enough. It is of course also the case if the markdown was edited from an external editor... so, let's keep it this way then.

**Comment by egolus** [comment]
So I add a function in `Preview`. How do I call it? `refresh` would be problematic because you use it for a different functionallity in other places (reloading the whole UI instead of just reloading the source of the current view)

**Comment by baudren** [comment]
Works fine, except that it messes up the `css` style of the page. When turning it on, it somehow switches the title and subtitles color... do you get the same thing on your machine?

If this is only a css thing, I would be to merge the PR, since the functionality works, and add this bug to the list of things to improve on the display of the page.

**Comment by egolus** [comment]
Hmm no, for me it looks the same as on the `devel` tree and as it looks on the screenshot on your homepage. Can you upload a screenshot?

**Comment by baudren** [comment]
Just checked that the `css` problem is not present on windows 8.1. I will post tonight screenshots of the issue, inside #40. Meanwhile, I am merging this, since it works. Thanks for the work, @egolus!

**Pull request merged**
