### PR TITLE
46 - New entry in contextmenu: preview

### PR DESCRIPTION
**Pull request by egolus**
this action directly loads the preview-tab for the selected notebook

### CODE REVIEW

**Comment by egolus** [comment]
so what do I do here?
- Picbutton has a new signal `previewSignal` that's emitted by the right click action `preview`
- this signal is handled by `Shelves.previewNotebook` that emits a signal `shelves.previewSignal`
- this signal is handled by `NoteOrganiser.previewNotebook` (this function allready handles the signal `Editing.loadNotebook`)

possible changes:
- different buttons for notebooks and folders that both inherit `Picbutton`. At the moment both have the right-click-actions but only for notebooks they are handled
- also emit `previewSignal` when shift-clicking the notebook in the library

**Comment by egolus** [comment]
here is a way to check for the modifier-keys: (shift-click etc.)
http://stackoverflow.com/questions/8772595/how-to-check-if-a-key-modifier-is-pressed-shift-ctrl-alt

**Comment by baudren** [comment]
Hey @egolus 
it looks pretty good!

One nitpick would be that, once shift clicked on the notebook to preview it, if I switch back to the editing pane, it is not the correct one loaded. It is a very simple fix, and I think it would improve it nicely. Otherwise, nice job, thank you!

**Comment by egolus** [comment]
so I need to set the tab in `Editing` to the notebook? All right, I'll look into it

**Comment by egolus** [comment]
ok, I'm switching the tab in the editor now.
Tell me, if I'm doing something stupid with the notebook-path. I'm getting the name, build a full path from it and then have to get the basename back for calling `Editing.switchNotebook`

and have you seen, what i wrote in gitter about the `PicButton` ? I was thinking to have a baseclass `PicButton` and two classes `PicNotebook` and `PicFolder` that inherit from the baseclass. So the actions `delete` and `preview` would be implemented in `PicNotebook`.

**Comment by baudren** [comment]
Ok, I agree, it might become cleanier to separate the two classes. Remove the `style` from the argument list, and perform the `paintEvent` and specific actions in the daughter classes.

Could you also add a test in `tests/test_frames.py`, the function `test_shelves`, to try and shift click and see if it opened the library, then going back to editing and checking that the index of the tab is the right one? This way we cover the new `preview` function.

**Comment by egolus** [comment]
@baudren Do you see any problem with this? The actions are only added for notebooks. If I understand it correctly, even if you would connect something to the signals on a folder, they just wouldn't get emited, right?

(travis seems to have some problems at the moment .. this was the second job today I had to restart manually because it failed and I was sure it shouldn't)

**Comment by baudren** [comment]
I just implemented a `delete` method for folders, since it does make sense - it is very similar to the delete notebook one, but checks if the folder does not contain files, and ask confirmation if it is the case. If it is empty, the delete will be immediate.

**Comment by egolus** [comment]
All right, this looks good

**Pull request merged**
