### PR TITLE
[WIP] set window icon

### PR DESCRIPTION
**Pull request by egolus**
First draft for the setting of the icon ( #31). The icon itself can still change, of course

### CODE REVIEW

**Comment by egolus** [comment]
I rebased this to the current devel

**Comment by baudren** [comment]
By the way, what is the status of this PR? Is it finished, or still WIP?

**Comment by egolus** [comment]
It's still WIP.
Right now, I just use the Notebook-Image as Icon. We should at least copy it as `WindowIcon.png` or something and use this in the code. Then we can later just override this picture with the new Image we wanted to draw.
Should I move the filename into `constants.py`

**Comment by baudren** [comment]
It could be a good idea to isolate it to `constants.py`, though it is not so likely to change (so not much drive to isolate it *that* much).

Also, as far as Linux is concerned, this seems to be working. It replaces the 'no icon' look in the taskbar with the notebook. However, there is no icon on the title bar of the app. On Windows, it acts oppositely: the taskbar keeps no icon (actually, the ipython icon...), but the title bar has the notebook icon. Do you get the same behaviour on your side?

**Comment by egolus** [comment]
Hmm. How do you start noteorganiser on windows? If I use `pythonw.exe` so I don't get a console, or if I call `noteorganiser.py` from an existing console so it doesn't create a **new** console, the icon is used for both the titlebar-icon and the taskbar-icon. If I use `python.exe` to create a new console that creates the QT window afterwards, windows combines the two icons and shows the standard python icon (of the console)

**Comment by baudren** [comment]
I start it with `python.exe` from Anaconda. If I use `pythonw.exe`, the task bar icon is replaced by a logo of Anaconda (at least I think it is one). None of the option actually let me see the notebook on the task bar.

**Comment by egolus** [comment]
hmhm, I don't know Anaconda. If you use `python` from there, does it start a new python console?

**Comment by baudren** [comment]
Well, there is some weird things going on when launching Anaconda from my terminal (babun, cygwin based). For instance, if I do not add the `-i` flag, I see no output until the program has finished running.

I would say that if you are satisfied on how it looks on your side, my peculiar situation does not matter much. It could be a configuration error on my side.

**Comment by egolus** [comment]
hmhm ok. Even if it's not showing every icon everywhere, it's still more than showing no icon at all

**Pull request merged**
