### PR TITLE
insert image

### PR DESCRIPTION
**Pull request by baudren**
Since the work by Egolus was on his fork, I could not modify the PR, so here is a new PR containing his work plus some tests.

### CODE REVIEW

**Comment by baudren** [comment]
I would suggest to merge this, and open a bug report for trying to fix the bug that breaks, even though it does not break locally.

**Comment by baudren** [comment]
Ah, I just realized: don't we want to add this functionality also from within the post creation? Because you probably think about an image at that time, not once the post is created. This should not require much more work, right?

**Comment by egolus** [comment]
You're right, I'll look into reusing the method with a new action inside the new-post form

**Comment by baudren** [comment]
This looks good. I am merging this now, thanks for the work!

**Pull request merged**
