### PR TITLE
Externaleditor

### PR DESCRIPTION
**Pull request by egolus**
So here's finally a draft for the external editor.

The popup doesn't check the commandline, but if it is valid, the opening with `Popen` should work

because it is in a subprocess, noteorganiser itself isn't blocked

### CODE REVIEW

**Comment by baudren** [comment]
Hello @egolus , thanks for PR. I tried it on my machine, but it does not work. Specifically, this line:
https://github.com/egolus/NoteOrganiser/blob/externaleditor/noteorganiser/popups.py#L244
At this point, as far as I understand, self.info.setExternalEditor is not defined. At least, when I click on the menu button, I get this stacktrace:

~~~
Traceback (most recent call last):
  File "/home/benjamin/Documents/Private/NoteOrganiser/noteorganiser/NoteOrganiser.py", line 122, in setExternalEditor
    self.popup = SetExternalEditor(self)
  File "noteorganiser/popups.py", line 230, in __init__
    self.initUI()
  File "noteorganiser/popups.py", line 244, in initUI
    self.commandlineEdit.setText(self.info.externalEditor)
AttributeError: 'Information' object has no attribute 'externalEditor'
~~~

**Comment by egolus** [comment]
You're right. I mixed something up when I rebased it before I opened the PR.

can you look at it now?

**Comment by baudren** [comment]
yep, that works now, and the tests are passing. Thanks! I think it is a first step - it would be nice if the file would be read again in NoteOrganiser when saved to disk (pushing the reload button might get old). But this is polishing, now that the feature is in.

**Comment by egolus** [comment]
@baudren yes, an automatic refresh would be nice. Not only when you open the editor by this button.
But I think, it should be set by a switch so you can turn it off and of course it should only refresh, when you didn't change anything in noteorganiser itself so you can't loose any changes you made.

I'll look into filesystem-monitoring..

**Pull request merged**
